name: cipher_quest
description: "Identity V themed cipher machine decoding app for school festival"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: 1.5.0
  web_socket_channel: ^3.0.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
